version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: krypto_api
    restart: unless-stopped
    env_file: .env
    environment:
      - API_URL=$API_URL
      - API_KEY=$API_KEY
      - BINANCE_URL=$BINANCE_URL
    ports:
      - 3001:3000
